[cursor-bibata-modern-ice]
version = "2.0.7"
source = "https://github.com/ful1e5/Bibata_Cursor/releases/download/v2.0.7/Bibata-Modern-Ice.tar.xz"
owner = "ful1e5"
description = "Open source, compact, and material designed cursor set that aims to improve the cursor experience for users. "

[[cursor-bibata-modern-ice.files]]
action = "sync"
target_root = "${XDG_DATA_HOME}/icons/Bibata-Modern-Ice"
paths = ["index.theme", "cursor.theme", "cursors"]

[hyprcursor-bibata-modern-ice]
version = "1.0.0"
source = "https://github.com/LOSEARDES77/Bibata-Cursor-hyprcursor/releases/download/1.0/hypr_Bibata-Modern-Ice.tar.gz"
owner = "LOSEARDES77"
description = "A hyprcursor build of Bibata-Modern-Ice"

[[hyprcursor-bibata-modern-ice.files]]
action = "sync"
target_root = "${XDG_DATA_HOME}/icons/Bibata-Modern-Ice"
paths = ["manifest.hl", "hyprcursors"]




#*
#! MaterialDesingIcons are now built into the Nerd Fonts  no need to download them
# TODO: Add systemwide installation
# * font-noto-sans-cjk-ttc
# * cursor-bibata-modern-ice
# * hyprcursor-bibata-modern-ice
