[wlogout]
    description = "A Wayland based logout menu"

[[wlogout.dependency]]
    pacman = [ "wlogout" ]

[[wlogout.files]]
    action      = "sync"
    paths       = ["wlogout"]
    source_root = "Configs/.config"
    target_root = "${XDG_CONFIG_HOME}"
