[wlogout]
    description = "A Wayland based logout menu"

[[wlogout.dependency]]
    pacman = [ "wlogout" ]

[[wlogout.files]]
    action      = "preserve"
    paths       = ["."]
    source_root = "Configs/.config/wlogout"
    target_root = "${XDG_CONFIG_HOME}/wlogout"
